### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by YangZiz** [hansen7/OcCo#36]
Hi@hansen7 :
  When I run on my own dataset, the following errors occur. What should I do
`Traceback (most recent call last):
  File "./OcCo_Torch/train_completion.py", line 253, in <module>
    main(args)
  File "./OcCo_Torch/train_completion.py", line 71, in main
    lmdb_train, args.batch_size, args.input_pts, args.gt_pts, is_training=True)
  File "/workspace/OcCo_Torch/OcCo_Torch/LMDB_DataFlow.py", line 77, in lmdb_dataflow
    df = dataflow.LMDBSerializer.load(lmdb_path, shuffle=False)
  File "/opt/conda/lib/python3.6/site-packages/tensorpack/dataflow/serialize.py", line 106, in load
    df = LMDBData(path, shuffle=shuffle)
  File "/opt/conda/lib/python3.6/site-packages/tensorpack/dataflow/format.py", line 91, in __init__
    self._set_keys(keys)
  File "/opt/conda/lib/python3.6/site-packages/tensorpack/dataflow/format.py", line 111, in _set_keys
    self.keys = loads(self.keys)
  File "/opt/conda/lib/python3.6/site-packages/tensorpack/utils/serialize.py", line 43, in loads_msgpack
    max_str_len=MAX_MSGPACK_LEN)
  File "/opt/conda/lib/python3.6/site-packages/msgpack_numpy.py", line 287, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
`

**Comment by hansen7** [comment]
Hi @YangZiz.

There might be two reasons:
- LMDB files are corrupted, you may need to re-download it.
- The version of msgpack version is not correct, see [OcCo_Torch/Requirements_Torch.txt](https://github.com/hansen7/OcCo/blob/master/OcCo_Torch/Requirements_Torch.txt)
